shibaribrasil:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: igneous-sandbox-381622       # <- substitua pelo nome real do seu projeto GCP
      dataset: dbt_dw                       # <- substitua pelo seu dataset no BigQuery
      threads: 2
      keyfile: C:\Git\key_project_sb.json
      location: us-east4